CREATE TABLE IF NOT EXISTS "users" (
	"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"email" TEXT NOT NULL UNIQUE,
	"password" TEXT,
	"mod" BOOLEAN NOT NULL,
	PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "products" (
	"product_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"usr_id" INTEGER NOT NULL UNIQUE,
	"name" TEXT NOT NULL,
	"published" DATE NOT NULL,
	"condition" TEXT NOT NULL,
	"price" MONEY NOT NULL,
	PRIMARY KEY("product_id")
);




CREATE TABLE IF NOT EXISTS "images" (
	"product_id" INTEGER NOT NULL UNIQUE,
	"data" VARBIT(1) NOT NULL UNIQUE,
	PRIMARY KEY("product_id", "data")
);




CREATE TABLE IF NOT EXISTS "categories" (
	"category_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT NOT NULL,
	PRIMARY KEY("category_id")
);




CREATE TABLE IF NOT EXISTS "products_categories" (
	"product_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"categpry_id" INTEGER NOT NULL,
	PRIMARY KEY("product_id", "categpry_id")
);




CREATE TABLE IF NOT EXISTS "pruchases" (
	"product_id" INTEGER NOT NULL,
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"date" DATE NOT NULL,
	"payment_method" TEXT NOT NULL,
	"confirmed" BOOLEAN NOT NULL,
	PRIMARY KEY("product_id", "user_id")
);


CREATE INDEX "pruchases_index_0"
ON "pruchases" ();
ALTER TABLE "products"
ADD FOREIGN KEY("usr_id") REFERENCES "users"("user_id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "images"
ADD FOREIGN KEY("product_id") REFERENCES "products"("product_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "products_categories"
ADD FOREIGN KEY("categpry_id") REFERENCES "categories"("category_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "products_categories"
ADD FOREIGN KEY("product_id") REFERENCES "products"("product_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pruchases"
ADD FOREIGN KEY("product_id") REFERENCES "products"("product_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pruchases"
ADD FOREIGN KEY("user_id") REFERENCES "users"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;