CREATE TABLE IF NOT EXISTS users (
	user_id SERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255),
	username VARCHAR(255) NOT NULL,
	mod BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
	product_id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL UNIQUE,
	title VARCHAR(255) NOT NULL,
	artist VARCHAR(255) NOT NULL,
	genre VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	condition VARCHAR(255) NOT NULL,
	published DATE NOT NULL,
	price NUMERIC NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS images (
	image_id SERIAL PRIMARY KEY,
	product_id INTEGER NOT NULL,
	data TEXT NOT NULL,
	FOREIGN KEY(product_id) REFERENCES products(product_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS categories (
	category_id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS products_categories (
	product_id INTEGER NOT NULL,
	category_id INTEGER NOT NULL,
	PRIMARY KEY(product_id, category_id),
	FOREIGN KEY(category_id) REFERENCES categories(category_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY(product_id) REFERENCES products(product_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS purchases (
	product_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	date DATE NOT NULL,
	payment_method VARCHAR(255) NOT NULL,
	confirmed BOOLEAN NOT NULL,
	PRIMARY KEY(product_id, user_id),
	FOREIGN KEY(product_id) REFERENCES products(product_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY(user_id) REFERENCES users(user_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);