CREATE TABLE IF NOT EXISTS users (
	user_id SERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255),
	username VARCHAR(255) NOT NULL,
	mod BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
	product_id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	title VARCHAR(255) NOT NULL,
	artist VARCHAR(255) NOT NULL,
	record_label VARCHAR(255) NOT NULL DEFAULT '',
	catalog_number VARCHAR(255) NOT NULL DEFAULT '',
	edition_country VARCHAR(255) NOT NULL DEFAULT '',
	description TEXT NOT NULL,
	sleeve_condition NUMERIC NOT NULL,
	record_condition NUMERIC NOT NULL,
	neighborhood VARCHAR(255) NOT NULL,
	province VARCHAR(255) NOT NULL,
	published DATE NOT NULL,
	price NUMERIC NOT NULL,
	available BOOLEAN NOT NULL DEFAULT TRUE,
	FOREIGN KEY(user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS images (
	image_id SERIAL PRIMARY KEY,
	product_id INTEGER NOT NULL,
	data BLOB NOT NULL,
	content_type VARCHAR(255) NOT NULL,
	FOREIGN KEY(product_id) REFERENCES products(product_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS categories (
	category_id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS products_categories (
	product_id INTEGER NOT NULL,
	category_id INTEGER NOT NULL,
	PRIMARY KEY(product_id, category_id),
	FOREIGN KEY(category_id) REFERENCES categories(category_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY(product_id) REFERENCES products(product_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS purchases (
	purchase_id SERIAL PRIMARY KEY,
	product_id INTEGER NOT NULL,
	buyer_user_id INTEGER NOT NULL,
	seller_user_id INTEGER NOT NULL,
	date DATE NOT NULL,
	payment_method VARCHAR(255) NOT NULL,
	confirmed BOOLEAN NOT NULL,
	FOREIGN KEY(product_id) REFERENCES products(product_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY(buyer_user_id) REFERENCES users(user_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY(seller_user_id) REFERENCES users(user_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS reviews (
	review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	purchase_id INTEGER NOT NULL UNIQUE,
	seller_id INTEGER NOT NULL,
	buyer_id INTEGER NOT NULL,
	score INTEGER NOT NULL CHECK (score >= 0 AND score <= 5),
	review VARCHAR(2000),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY(purchase_id) REFERENCES purchases(purchase_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(seller_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(buyer_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Seed default categories (genres) for testing
INSERT INTO categories (name) VALUES ('Rock');
INSERT INTO categories (name) VALUES ('Pop');
INSERT INTO categories (name) VALUES ('Jazz');
INSERT INTO categories (name) VALUES ('Electronic');
INSERT INTO categories (name) VALUES ('Classical');
INSERT INTO categories (name) VALUES ('Hip Hop');
INSERT INTO categories (name) VALUES ('Indie');
INSERT INTO categories (name) VALUES ('Reggaeton');

