package ar.edu.itba.paw.persistence;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;

import ar.edu.itba.paw.models.Notification;
import ar.edu.itba.paw.models.NotificationType;
import ar.edu.itba.paw.models.PaginatedResult;
import ar.edu.itba.paw.models.Product;
import ar.edu.itba.paw.models.User;

@Rollback
@Transactional
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = TestConfiguration.class)
public class NotificationJpaDaoTest {

    @Autowired
    private NotificationJpaDao notificationDao;

    @PersistenceContext
    private EntityManager em;

    private static boolean notificationIdGeneratorInstalled = false;

    @BeforeEach
    public void setUpSchema() {
        em.createNativeQuery(
                "CREATE TABLE IF NOT EXISTS user_follows (" +
                        "follower_id INTEGER NOT NULL, " +
                        "followed_id INTEGER NOT NULL, " +
                        "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, " +
                        "PRIMARY KEY (follower_id, followed_id))")
                .executeUpdate();
        if (!notificationIdGeneratorInstalled) {
            // createForAllFollowers() inserts natively without notification_id, relying on the
            // sequence default schema.sql provides in production. The Hibernate-generated test
            // table lacks it, so add an identity generator started above any id Hibernate's
            // own sequence will hand out, to avoid collisions between the two
            em.createNativeQuery(
                    "ALTER TABLE notifications ALTER COLUMN notification_id " +
                            "GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000)")
                    .executeUpdate();
            notificationIdGeneratorInstalled = true;
        }
    }

    private User createUser(final String username) {
        final User user = new User(
                username + "@test.com",
                "password",
                username,
                false,
                true,
                false,
                "Juan",
                "Perez",
                null,
                null,
                null,
                null,
                null,
                null);
        em.persist(user);
        em.flush();
        return user;
    }

    private Product createProduct(final User user, final String title) {
        final Product product = new Product(
                user.getId(),
                title,
                "Artist",
                "Label",
                "CAT-" + title,
                "Argentina",
                Collections.emptyList(),
                "Description",
                BigDecimal.valueOf(8),
                BigDecimal.valueOf(9),
                LocalDate.now(),
                BigDecimal.valueOf(1000),
                1);
        em.persist(product);
        em.flush();
        return product;
    }

    private void follow(final User follower, final User followed) {
        em.createNativeQuery("INSERT INTO user_follows (follower_id, followed_id) VALUES (:followerId, :followedId)")
                .setParameter("followerId", follower.getId())
                .setParameter("followedId", followed.getId())
                .executeUpdate();
    }

    private void setCreatedAt(final Notification notification, final LocalDateTime createdAt) {
        em.createQuery("UPDATE Notification n SET n.createdAt = :createdAt WHERE n.notificationId = :id")
                .setParameter("createdAt", createdAt)
                .setParameter("id", notification.getNotificationId())
                .executeUpdate();
    }

    private static List<Long> ids(final PaginatedResult<Notification> page) {
        return page.getResults().stream()
                .map(Notification::getNotificationId)
                .collect(Collectors.toList());
    }

    @Test
    public void testCreate() {
        // Arrange
        final User recipient = createUser("notif_recipient");
        final User actor = createUser("notif_actor");
        final Product product = createProduct(actor, "Album");

        // Act
        final Notification notification = notificationDao.create(
                NotificationType.PURCHASE_STATUS,
                recipient.getId(),
                actor.getId(),
                product.getId(),
                99L,
                "PAID");

        // Assert
        em.flush();
        em.clear();

        final Notification persisted = em.find(Notification.class, notification.getNotificationId());

        Assertions.assertNotNull(persisted);
        Assertions.assertEquals(recipient.getId().longValue(), persisted.getRecipientUserId());
        Assertions.assertEquals(actor.getId(), persisted.getActorUserId());
        Assertions.assertEquals(NotificationType.PURCHASE_STATUS, persisted.getType());
        Assertions.assertEquals(product.getId(), persisted.getProductId());
        Assertions.assertEquals(Long.valueOf(99L), persisted.getPurchaseId());
        Assertions.assertEquals("PAID", persisted.getPurchaseStatus());
        Assertions.assertNotNull(persisted.getCreatedAt());
        Assertions.assertNull(persisted.getReadAt());
    }

    @Test
    public void testCreateForAllFollowers() {
        // Arrange
        final User seller = createUser("notif_seller");
        final User follower1 = createUser("notif_follower_1");
        final User follower2 = createUser("notif_follower_2");
        createUser("notif_non_follower");
        final Product product = createProduct(seller, "New Album");

        follow(follower1, seller);
        follow(follower2, seller);

        // Act
        notificationDao.createForAllFollowers(NotificationType.NEW_PRODUCT, seller.getId(), product.getId());

        // Assert
        em.flush();
        em.clear();

        final List<Notification> notifications = em.createQuery(
                "FROM Notification n", Notification.class).getResultList();

        Assertions.assertEquals(2, notifications.size());

        final Set<Long> recipientIds = notifications.stream()
                .map(Notification::getRecipientUserId)
                .collect(Collectors.toSet());
        Assertions.assertEquals(Set.of(follower1.getId(), follower2.getId()), recipientIds);

        for (final Notification notification : notifications) {
            Assertions.assertEquals(NotificationType.NEW_PRODUCT, notification.getType());
            Assertions.assertEquals(seller.getId(), notification.getActorUserId());
            Assertions.assertEquals(product.getId(), notification.getProductId());
            Assertions.assertNotNull(notification.getCreatedAt());
            Assertions.assertNull(notification.getReadAt());
        }
    }

    @Test
    public void testFindByRecipient() {
        // Arrange
        final User recipient = createUser("find_recipient");
        final User other = createUser("find_other");
        final User actor = createUser("find_actor");

        final Notification oldestFollow = notificationDao.create(
                NotificationType.FOLLOW, recipient.getId(), actor.getId(), null, null, null);
        final Notification middleNewProduct = notificationDao.create(
                NotificationType.NEW_PRODUCT, recipient.getId(), actor.getId(), null, null, null);
        final Notification newestFollow = notificationDao.create(
                NotificationType.FOLLOW, recipient.getId(), actor.getId(), null, null, null);
        notificationDao.create(
                NotificationType.FOLLOW, other.getId(), actor.getId(), null, null, null);
        em.flush();

        final LocalDateTime base = LocalDateTime.now();
        setCreatedAt(oldestFollow, base.minusHours(3));
        setCreatedAt(middleNewProduct, base.minusHours(2));
        setCreatedAt(newestFollow, base.minusHours(1));
        em.clear();

        // Act
        final PaginatedResult<Notification> firstPage =
                notificationDao.findByRecipient(recipient.getId(), null, 1, 2);
        final PaginatedResult<Notification> secondPage =
                notificationDao.findByRecipient(recipient.getId(), null, 2, 2);
        final PaginatedResult<Notification> followsOnly =
                notificationDao.findByRecipient(recipient.getId(), NotificationType.FOLLOW, 1, 10);
        final PaginatedResult<Notification> none =
                notificationDao.findByRecipient(actor.getId(), null, 1, 10);

        // Assert
        Assertions.assertEquals(3, firstPage.getTotalCount());
        Assertions.assertIterableEquals(
                List.of(newestFollow.getNotificationId(), middleNewProduct.getNotificationId()),
                ids(firstPage));

        Assertions.assertIterableEquals(
                List.of(oldestFollow.getNotificationId()),
                ids(secondPage));

        Assertions.assertEquals(2, followsOnly.getTotalCount());
        Assertions.assertIterableEquals(
                List.of(newestFollow.getNotificationId(), oldestFollow.getNotificationId()),
                ids(followsOnly));

        Assertions.assertEquals(0, none.getTotalCount());
        Assertions.assertTrue(none.getResults().isEmpty());
    }

    @Test
    public void testCountUnread() {
        // Arrange
        final User recipient = createUser("count_recipient");
        final User other = createUser("count_other");
        final User actor = createUser("count_actor");

        notificationDao.create(NotificationType.FOLLOW, recipient.getId(), actor.getId(), null, null, null);
        notificationDao.create(NotificationType.NEW_PRODUCT, recipient.getId(), actor.getId(), null, null, null);
        final Notification read = notificationDao.create(
                NotificationType.FOLLOW, recipient.getId(), actor.getId(), null, null, null);
        notificationDao.create(NotificationType.FOLLOW, other.getId(), actor.getId(), null, null, null);
        em.flush();

        em.createQuery("UPDATE Notification n SET n.readAt = :now WHERE n.notificationId = :id")
                .setParameter("now", LocalDateTime.now())
                .setParameter("id", read.getNotificationId())
                .executeUpdate();
        em.clear();

        // Act & Assert
        Assertions.assertEquals(2L, notificationDao.countUnread(recipient.getId()));
        Assertions.assertEquals(1L, notificationDao.countUnread(other.getId()));
        Assertions.assertEquals(0L, notificationDao.countUnread(actor.getId()));
    }

    @Test
    public void testMarkRead() {
        // Arrange
        final User recipient = createUser("mark_recipient");
        final User other = createUser("mark_other");
        final User actor = createUser("mark_actor");

        final Notification first = notificationDao.create(
                NotificationType.FOLLOW, recipient.getId(), actor.getId(), null, null, null);
        final Notification second = notificationDao.create(
                NotificationType.NEW_PRODUCT, recipient.getId(), actor.getId(), null, null, null);
        final Notification untouched = notificationDao.create(
                NotificationType.FOLLOW, recipient.getId(), actor.getId(), null, null, null);
        final Notification othersNotification = notificationDao.create(
                NotificationType.FOLLOW, other.getId(), actor.getId(), null, null, null);
        em.flush();

        // Act: also pass another user's id to check it is not marked
        notificationDao.markRead(recipient.getId(), List.of(
                first.getNotificationId(),
                second.getNotificationId(),
                othersNotification.getNotificationId()));

        // Assert
        em.flush();
        em.clear();

        Assertions.assertNotNull(em.find(Notification.class, first.getNotificationId()).getReadAt());
        Assertions.assertNotNull(em.find(Notification.class, second.getNotificationId()).getReadAt());
        Assertions.assertNull(em.find(Notification.class, untouched.getNotificationId()).getReadAt());
        Assertions.assertNull(em.find(Notification.class, othersNotification.getNotificationId()).getReadAt());
    }

    @Test
    public void testMarkAllRead() {
        // Arrange
        final User recipient = createUser("mark_all_recipient");
        final User other = createUser("mark_all_other");
        final User actor = createUser("mark_all_actor");

        final Notification first = notificationDao.create(
                NotificationType.FOLLOW, recipient.getId(), actor.getId(), null, null, null);
        final Notification second = notificationDao.create(
                NotificationType.NEW_PRODUCT, recipient.getId(), actor.getId(), null, null, null);
        final Notification othersNotification = notificationDao.create(
                NotificationType.FOLLOW, other.getId(), actor.getId(), null, null, null);
        em.flush();

        // Act
        notificationDao.markAllRead(recipient.getId());

        // Assert
        em.flush();
        em.clear();

        Assertions.assertNotNull(em.find(Notification.class, first.getNotificationId()).getReadAt());
        Assertions.assertNotNull(em.find(Notification.class, second.getNotificationId()).getReadAt());
        Assertions.assertNull(em.find(Notification.class, othersNotification.getNotificationId()).getReadAt());
    }
}
