package ar.edu.itba.paw.persistence;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;

import ar.edu.itba.paw.models.PendingNotification;
import ar.edu.itba.paw.models.Product;
import ar.edu.itba.paw.models.User;

@Rollback
@Transactional
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = TestConfiguration.class)
public class PendingNotificationJpaDaoTest {

    @Autowired
    private PendingNotificationJpaDao pendingNotificationDao;

    @PersistenceContext
    private EntityManager em;

    private static boolean notificationIdGeneratorInstalled = false;

    @BeforeEach
    public void setUpSchema() {
        em.createNativeQuery(
                "CREATE TABLE IF NOT EXISTS user_follows (" +
                        "follower_id INTEGER NOT NULL, " +
                        "followed_id INTEGER NOT NULL, " +
                        "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, " +
                        "PRIMARY KEY (follower_id, followed_id))")
                .executeUpdate();
        if (!notificationIdGeneratorInstalled) {
            // createForAllFollowersOf() inserts natively without notification_id, relying on the
            // sequence default schema.sql provides in production. The Hibernate-generated test
            // table lacks it, so add an identity generator started above any id Hibernate's
            // own sequence will hand out, to avoid collisions between the two
            em.createNativeQuery(
                    "ALTER TABLE pending_notifications ALTER COLUMN notification_id " +
                            "GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000)")
                    .executeUpdate();
            notificationIdGeneratorInstalled = true;
        }
    }

    private User createUser(final String username) {
        final User user = new User(
                username + "@test.com",
                "password",
                username,
                false,
                true,
                false,
                "Juan",
                "Perez",
                null,
                null,
                null,
                null,
                null,
                null);
        em.persist(user);
        em.flush();
        return user;
    }

    private Product createProduct(final User user, final String title) {
        final Product product = new Product(
                user.getId(),
                title,
                "Artist",
                "Label",
                "CAT-" + title,
                "Argentina",
                Collections.emptyList(),
                "Description",
                BigDecimal.valueOf(8),
                BigDecimal.valueOf(9),
                LocalDate.now(),
                BigDecimal.valueOf(1000),
                1);
        em.persist(product);
        em.flush();
        return product;
    }

    private void follow(final User follower, final User followed) {
        em.createNativeQuery("INSERT INTO user_follows (follower_id, followed_id) VALUES (:followerId, :followedId)")
                .setParameter("followerId", follower.getId())
                .setParameter("followedId", followed.getId())
                .executeUpdate();
    }

    private PendingNotification insertPendingNotification(final User follower, final Product product) {
        final PendingNotification pendingNotification = new PendingNotification(follower.getId(), product.getId());
        em.persist(pendingNotification);
        em.flush();
        return pendingNotification;
    }

    @Test
    public void testCreate() {
        // Arrange
        final User follower = createUser("pending_follower");
        final User seller = createUser("pending_seller");
        final Product product = createProduct(seller, "Album");

        // Act
        pendingNotificationDao.create(follower.getId(), product.getId());

        // Assert
        em.flush();
        em.clear();

        final List<PendingNotification> all = em.createQuery(
                "FROM PendingNotification pn", PendingNotification.class).getResultList();

        Assertions.assertEquals(1, all.size());
        final PendingNotification persisted = all.get(0);
        Assertions.assertNotNull(persisted.getNotificationId());
        Assertions.assertEquals(follower.getId().longValue(), persisted.getFollowerUserId());
        Assertions.assertEquals(product.getId().longValue(), persisted.getProductId());
        Assertions.assertNotNull(persisted.getCreatedAt());
    }

    @Test
    public void testCreateForAllFollowersOf() {
        // Arrange
        final User seller = createUser("pending_seller_all");
        final User follower1 = createUser("pending_follower_1");
        final User follower2 = createUser("pending_follower_2");
        createUser("pending_non_follower");
        final Product product = createProduct(seller, "New Album");

        follow(follower1, seller);
        follow(follower2, seller);

        // Act
        pendingNotificationDao.createForAllFollowersOf(seller.getId(), product.getId());

        // Assert
        em.clear();

        final List<PendingNotification> all = em.createQuery(
                "FROM PendingNotification pn", PendingNotification.class).getResultList();

        Assertions.assertEquals(2, all.size());

        final Set<Long> followerIds = all.stream()
                .map(PendingNotification::getFollowerUserId)
                .collect(Collectors.toSet());
        Assertions.assertEquals(Set.of(follower1.getId(), follower2.getId()), followerIds);

        for (final PendingNotification pendingNotification : all) {
            Assertions.assertEquals(product.getId().longValue(), pendingNotification.getProductId());
            Assertions.assertNotNull(pendingNotification.getCreatedAt());
        }
    }

    @Test
    public void testFindAll() {
        // Arrange
        final User firstFollower = createUser("find_all_follower_1");
        final User secondFollower = createUser("find_all_follower_2");
        final User thirdFollower = createUser("find_all_follower_3");
        final User seller = createUser("find_all_seller");
        final Product product = createProduct(seller, "Album");

        // Insert out of order to verify the ordering by follower id
        insertPendingNotification(thirdFollower, product);
        insertPendingNotification(firstFollower, product);
        insertPendingNotification(secondFollower, product);
        em.clear();

        // Act
        final List<PendingNotification> all = pendingNotificationDao.findAll();

        // Assert
        final List<Long> followerIds = all.stream()
                .map(PendingNotification::getFollowerUserId)
                .collect(Collectors.toList());
        Assertions.assertIterableEquals(
                List.of(firstFollower.getId(), secondFollower.getId(), thirdFollower.getId()),
                followerIds);
    }

    @Test
    public void testDeleteByIds() {
        // Arrange
        final User follower = createUser("delete_follower");
        final User seller = createUser("delete_seller");
        final Product product = createProduct(seller, "Album");

        final PendingNotification first = insertPendingNotification(follower, product);
        final PendingNotification second = insertPendingNotification(follower, product);
        final PendingNotification third = insertPendingNotification(follower, product);

        // Act
        pendingNotificationDao.deleteByIds(List.of(first.getNotificationId(), third.getNotificationId()));

        // Assert
        em.clear();

        final List<PendingNotification> remaining = em.createQuery(
                "FROM PendingNotification pn", PendingNotification.class).getResultList();

        Assertions.assertEquals(1, remaining.size());
        Assertions.assertEquals(second.getNotificationId(), remaining.get(0).getNotificationId());

        // An empty id list is a no-op
        pendingNotificationDao.deleteByIds(Collections.emptyList());
        pendingNotificationDao.deleteByIds(null);
        em.clear();

        Assertions.assertEquals(1, em.createQuery(
                "FROM PendingNotification pn", PendingNotification.class).getResultList().size());
    }
}
